apiVersion: apps/v1
kind: Application
metadata:
  name: api-application
  namespace: argocd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: trivial-go-web-app
  source:
    repoURL: https://github.com/anet01/server.git
    targetRevision: master
    path: master
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
