apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: myapp
          image: test/argocd-app:1.2
          ports:
            - containerPort: 8080
